### ISSUE TITLE
the starting date for recording is incorrect

### ISSUE THREAD

**Issue by nosarthur** [repo-analytics/repo-analytics.github.io#10]
In the page of https://repo-analytics.github.io/nosarthur/gita

it shows `Recoding analytics since 2019-10-21`, but in the plots, the starting date is 10-06

**Comment by timqian** [comment]
This is expected
The GitHub traffic API allows us to get traffic of last 15 days. So when we start recording, we get earler traffic data too~

**Comment by nosarthur** [comment]
I see. Thanks
